			<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0">
				<TR>
					<TD><IMG SRC="images/tb_left_off.gif"></TD><TD VALIGN="MIDDLE" BACKGROUND="images/tb_bg_off.gif" onClick="document.location.href='edit_test1.php?course_id=<?php echo $course_id; ?>&ID=<?php echo $ID; ?>&ID=<?php echo $ID;?>';" onMouseOver="this.style.cursor='default';"><SPAN CLASS="ttg"><?php if($tsection==1){echo"<B>";}?>Properties</TD><TD><IMG SRC="images/tb_middle_off.gif"></TD>
					<TD VALIGN="MIDDLE" BACKGROUND="images/tb_bg_off.gif" onClick="document.location.href='edit_test2.php?course_id=<?php echo $course_id;?>&ID=<?php echo $ID;?>&ID=<?php echo $ID;?>';" onMouseOver="this.style.cursor='default';"><SPAN CLASS="ttg"><?php if($tsection==2){echo"<B>";}?>Test Qestions</TD><TD><IMG SRC="images/tb_right_off.gif"></TD>					
				</TR>
			</TABLE>