			<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0">
				<TR>
					<TD><IMG SRC="images/tb_left_off.gif"></TD><TD VALIGN="MIDDLE" BACKGROUND="images/tb_bg_off.gif" onClick="document.location.href='edit_subtopic1.php?course_id=<?php echo $course_id;?>&ID=<?php echo $ID;?>';" onMouseOver="this.style.cursor='default';"><SPAN CLASS="ttg"><?php if($tsection==1){echo"<B>";}?>Properties</TD><TD><IMG SRC="images/tb_middle_off.gif"></TD>
					<TD VALIGN="MIDDLE" BACKGROUND="images/tb_bg_off.gif" onClick="document.location.href='edit_subtopic2.php?course_id=<?php echo $course_id;?>&ID=<?php echo $ID;?>';" onMouseOver="this.style.cursor='default';"><SPAN CLASS="ttg"><?php if($tsection==2){echo"<B>";}?>Content</TD><TD><IMG SRC="images/tb_middle_off.gif"></TD>
					<TD VALIGN="MIDDLE" BACKGROUND="images/tb_bg_off.gif" onClick="document.location.href='edit_subtopic3.php?course_id=<?php echo $course_id;?>&ID=<?php echo $ID;?>';" onMouseOver="this.style.cursor='default';"><SPAN CLASS="ttg"><?php if($tsection==3){echo"<B>";}?>Code</TD><TD><IMG SRC="images/tb_middle_off.gif"></TD>
					<TD VALIGN="MIDDLE" BACKGROUND="images/tb_bg_off.gif" onMouseOver="this.style.cursor='default';"><SPAN CLASS="ttg"><?php if($section==4){echo"<B>";}?><FONT COLOR="#909090">Widgets</TD><TD><IMG SRC="images/tb_right_off.gif"></TD>					
				</TR>
			</TABLE>