<HTML>
<HEAD>
<TITLE>:::APPLICATION:::</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
</HEAD>

<FRAMESET ROWS="27,*" ID="toolbar" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0" COLS="*"> 
  <FRAME NAME="header" SCROLLING="NO" noresize SRC="course_list_header.php" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0">
  <FRAME NAME="list" SCROLLING="AUTO" noresize SRC="course_list.php" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0">	
</FRAMESET>

<NOFRAMES><BODY BGCOLOR="#FFFFFF"  TOPMARGIN="0" LEFTMARGIN="0" MARGINHEIGHT="0" MARGINWIDTH="0"></NOFRAMES>



</BODY>

</HTML>

