.input {FONT-FAMILY:VERDANA;FONT-SIZE:11;border: ridge 1px; TEXT-ALIGN: left;BACKGROUND:#EFF7FF}
.input3 {FONT-FAMILY:VERDANA;FONT-SIZE:12;BORDER-TOP:#336699 1px solid;BORDER-RIGHT:#336699 1px solid;BORDER-LEFT:#336699 1px solid;BORDER-BOTTOM:#336699 1px solid;BACKGROUND:#FFFFFF}
.ttl {FONT-FAMILY:VERDANA;FONT-SIZE:12;COLOR:#000000;}
.ttg {FONT-FAMILY:VERDANA;FONT-SIZE:10;COLOR:#000000;}
.hdr {FONT-FAMILY:VERDANA;FONT-SIZE:12;COLOR:#000000;FONT-WEIGHT:BOLD;}
.submit {FONT-FAMILY:VERDANA;FONT-SIZE:10;BACKGROUND:#EFF7FF}
BODY {
	BORDER-RIGHT: 0px; BORDER-TOP: 0px;
	SCROLLBAR-HIGHLIGHT-COLOR: #EFF7FF; 
	BORDER-LEFT: 0px; 
	SCROLLBAR-SHADOW-COLOR: #336699; 
	SCROLLBAR-3DLIGHT-COLOR: #ffffff; 
	SCROLLBAR-ARROW-COLOR: #000000; 
	SCROLLBAR-TRACK-COLOR: #EFF7FF; 
	BORDER-BOTTOM: 0px; 
	SCROLLBAR-DARKSHADOW-COLOR: #ffffff; 
	SCROLLBAR-BASE-COLOR: #93BEE2
}