<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>Untitled</title>
</head>

<body BGCOLOR="#93BEE2" TOPMARGIN="0" RIGHTMARGIN="0" LEFTMARGIN="0" BOTTOMMARGIN="0">
<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=100%>
<TR>
<TD BGCOLOR="#FFFFFF"><IMG SRC="spcr.gif" WIDTH="20" HEIGHT="1"></TD>
</TR>
<TR>
<TD BGCOLOR="#336699"><IMG SRC="spcr.gif" WIDTH="20" HEIGHT="1"></TD>
</TR>
<TR>
<TD BGCOLOR="#000000"><IMG SRC="spcr.gif" WIDTH="20" HEIGHT="1"></TD>
</TR>
</TABLE>
</body>
</html>
