<HTML>
<HEAD>
<TITLE>:::APPLICATION:::</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
</HEAD>

<FRAMESET  COLS="300,*" ROWS="*" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0"> 
    <FRAMESET  COLS="*" ROWS="60,*" FRAMEBORDER="YES" BORDER="1" FRAMESPACING="0"> 
      <FRAME NAME="group_list_top" SCROLLING="NO" noresize SRC="group_list_top.php" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0" BORDERCOLOR="#336699">
      <FRAME NAME="group_list" SRC="group_list.php" FRAMEBORDER="NO" BORDER="1" FRAMESPACING="0" BORDERCOLOR="#336699"> 	
    </FRAMESET>
      <FRAME NAME="details" SCROLLING="NO" noresize SRC="frame_group_details.php" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0" BORDERCOLOR="#336699">
</FRAMESET>
<NOFRAMES><BODY BGCOLOR="#FFFFFF"  TOPMARGIN="0" LEFTMARGIN="0" MARGINHEIGHT="0" MARGINWIDTH="0"></NOFRAMES>

</BODY>
</HTML>
