<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>Untitled</title>
</head>

<FRAMESET ROWS="100,*,0"  ID="objectManager" COLS="*" FRAMEBORDER="YES" BORDER="0" FRAMESPACING="0">
	<FRAME NAME="object_top" SCROLLING="NO" SRC="object_top.php" FRAMEBORDER="NO" BORDER="0" FRAMESPACING="0">
	<FRAME NAME="object_main" noresize SRC="object_manager.php" FRAMEBORDER="NO" BORDER="0" BORDERCOLOR="#336699" FRAMESPACING="0">
	<FRAME NAME="object_tree" SCROLLING="NO" SRC="object_tree.php" FRAMEBORDER="NO" BORDER="0" BORDERCOLOR="#336699" FRAMESPACING="0">
</FRAMESET>	

<NOFRAMES><BODY BGCOLOR="#FFFFFF" TOPMARGIN="0" LEFTMARGIN="0" MARGINHEIGHT="0" MARGINWIDTH="0"></NOFRAMES>

</BODY>
</HTML>
